### PR TITLE
Downloading session and graph packets script

### PR DESCRIPTION
**Pull request by acourt**
Not the most high quality but I want to merge this in right now so that people can start using it right away. It is part of #57 that was not merged into master yet.

### CODE REVIEW

**Comment by souellet-ms** [comment]
Est-ce vraiment utile de garder streamExample.py ?

**Comment by acourt** [comment]
Nope, good catch.

**Comment by souellet-ms** [comment]
In addition, the new example and the new NeblinaAPI function will not work with the current neblina global definitions. They use the old one...

**Comment by acourt** [comment]
Will use the colibri util instead

**Pull request closed without merging**
